lab_3/urls.py
from django.urls import path
from .views import *

# Create your views here.
app_name = "lab_3"

urlpatterns = [
    path('', index, name="index"),
    path('add_status', add_status, name="add_status"),
    path('myprofile', myprofile, name="myprofile"),
    path('registro', registro, name="registro"),
    path('check_email/', check_email, name='check_email'),
    path('save_subscriber/', save_subscriber, name='save_subscriber'),
    path('list-subscriber/', listSubscriber, name='listSubscriber'),
    path('delete/<int:id>', bigdelete, name='delete')
]

ppw/urls.py
from django.contrib import admin
from django.urls import path, include
import story4.urls as story4
import story9.urls as story9

app_name="tryout2"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('story4/', include((story4, story4), namespace="story4")),
    path('', include("lab_3.urls", "lab_3")),
    path('library/', include((story9, story9), namespace='story9')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('tryout/', include("tryout.urls","tryout")),
    path('deathnote/', include("tryout2.urls","tryout2"))
]

lab_3/models.py
from django.db import models


# Create your models here.

class Status(models.Model):
    id = models.AutoField(primary_key=True)
    forms = models.CharField(max_length=200)


class Subscriber(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=50)

lab_3/forms.py
from django import forms
from datetime import datetime

class Forms(forms.Form):
    status_attrs = {
        "type": "text",
        "placeholder": "Hello, how are you ?",
        "class": "search-text",
        "name": "newstatus"
    }
    status = forms.CharField(max_length=200, required=True, widget=forms.TextInput(attrs=status_attrs))



class Project_Form(forms.Form):
    pass_attrs = {
        'type': 'password',
        'class': 'form-control',
        'id': 'pass-form',
        'placeholder': 'Password',
    }
    email_attrs = {
        'name': 'email',
        'type': 'text',
        'class': 'form-control',
        'id': 'email-form',
        'placeholder': 'email@example.com'
    }
    name_attrs = {
        'type': 'text',
        'class': 'form-control',
        'id': 'name-form',
        'placeholder': 'Input Your Name'

    }
    name = forms.CharField(max_length=50, error_messages={"required": "Please enter your name"},
                           widget=forms.TextInput(attrs=name_attrs))
    email = forms.EmailField(error_messages={"required": "Please enter a valid email"}, max_length=100, label='Email',
                             required=True, widget=forms.EmailInput(attrs=email_attrs))
    password = forms.CharField(label='Password', required=True, max_length=20, min_length=6,
                               widget=forms.PasswordInput(attrs=pass_attrs),
                               error_messages={"min_length": "password must be longer than 5 characters"})

lab_3/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from .forms import *
from .models import *
from django.core.validators import validate_email

# Create your views here.

response = {}


def index(request):
    response = {
        'status': Forms,
        'events': Status.objects.all()
    }
    return render(request, "to_do_list.html", response)


def add_status(request):
    forms = Forms(request.POST)
    if request.method == "POST":
        if forms.is_valid():
            clean = forms.cleaned_data
            status = Status()
            status.forms = clean['status']
            status.save()
            print(status)
            return HttpResponseRedirect('/')
    else:
        return request, 'to_do_list.html'


def bigdelete(request, id):
    deletion = get_object_or_404(Status, pk=id)
    deletion.delete()
    return HttpResponseRedirect('/')


def myprofile(request):
    return render(request, "myprofile.html")


def registro(request):
    response = {'subscribe_form': Project_Form
                }
    context = {'subscribe': 'active'}
    html = "registo.html"
    return render(request, html, response)


def check_email(request):
    try:
        print(request.POST['email'])
        validate_email(request.POST['email'])
    except:
        return JsonResponse({
            'message': 'Email format is wrong!',
            'status': 'fail'
        })

    exist = Subscriber.objects.filter(email=request.POST['email'])

    if exist:
        return JsonResponse({
            'message': 'e-mail is already exist',
            'status': 'fail'
        })

    return JsonResponse({
        'message': 'Email can be used',
        'status': 'success'
    })


def save_subscriber(request):
    if request.method == "POST":
        subscriber = Subscriber(
            email=request.POST['email'],
            name=request.POST['name'],
            password=request.POST['password']
        )
        subscriber.save()

        return JsonResponse({
            'message': 'Registration Done! Thank you'
        }, status=200)
    else:
        return JsonResponse({
            'message': "There's no GET method here!"
        }, status=403)


def listSubscriber(request):
    all_subs = Subscriber.objects.all().values()
    subs = list(all_subs)
    return JsonResponse({'all_subs': subs})

lab_3/templates/myprofile.html
{% load staticfiles %}
<html>

<head>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/stylecopy.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static "js/profile.js" %}"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,300,600,800,900" rel="stylesheet" type="text/css">
</head>
<title>
    Profile
</title>
<body>
<div id="progressbar"></div>
<div id="dermatologist" style="display: none">
<div class="class1" style="background-color:#000;">
    <div style="padding-right:1rem">
        <h1 style="color:white; text-align:right; padding-top:2rem">MUHAMMAD</h1>
        <h1 style="color:#c4c4c4; text-align:right; ">NAUFAL</h1>
        <h1 style="color:white; text-align:right;">IlRBAHHANA</h1>
        <h2 style="color:white; text-align:right;padding-top:10px">1706019425</h2>
    </div>
    <hr>
    <p class="pclass1">Address: BSD Blok H-4 No 6 Sektor 1-1 Tangerang Selatan Banten<br>
        Phone Number: 087871786040<br>
        Majoring: Computer Science<br>
        Hobbies: Sports, Video game, Singing<br>
        Motto: Melakukan segala hal dengan nama Allah<br>
        Bio :I am a bright and happy person, i tend to cheer people.<br>
        Also a hardworker and passionate student.</p>
</div>

<div class="class2" style="background-color:white;padding-top: -2px">
    <div class="center">
        <img src="{% static 'image/me.jpeg' %}" imag-hover="tooltip" title="This is me"
             class="rounded-circle mx-auto d-block" height="250" width="200">
        <h1 style="text-align:center;">SKILLS</h1>
    </div>
    <div class="picture">
        <img src="{% static 'image/skills.png' %}" class="rounded mx-auto d-block" height="200" width="400">
    </div>
    <h2 style="margin-left: 20%;margin-top: 2%"> Pick your theme !</h2>
    <div class="btn-group btn-group-toggle" data-toggle="buttons" style="padding-left:30%">
        <label class="btn btn-outline-secondary">
            <input type="radio" name="options" id="option1" autocomplete="off" checked> Theme 1
        </label>
        <label class="btn btn-outline-success">
            <input type="radio" name="options" id="option2" autocomplete="off"> Theme 2
        </label>
    </div>
</div>

<div class="class3">
    <div id="accordion">
        <h3>Activity</h3>
        <div>
            <p>
            <ul>
                <li>I like to eat</li>
                <li>Do sports</li>
                <li>play video games</li>
            </ul>
            </p>
        </div>
        <h3>Organisation / Committees</h3>
        <div>
            <p>
            <ul>
                <li>OH Fasilkom UI</li>
                <li>PDK CS League</li>
                <li>Stage Compfest X</li>
                <li>Media & PR Asian Games Volunteer</li>
            </ul>
            </p>
        </div>
        <h3>Achievements</h3>
        <div>
            <ul>
                <li>Top 10 Best Startup Worldwide with INAGRI</li>
                <li>surviving fasilkom</li>
            </ul>
        </div>
    </div>
    <div style="padding-top: 1rem;">
    <a class="btn btn-danger btn-lg btn-block" href="{% url 'lab_3:registro' %}" role="button">Register !</a>
    </div>
    </div>
</div>
</body>
</html>

lab_3/templates/registo.html
{% extends "navbar.html" %}
{% block content %}
    {% load staticfiles %}

    <html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
              integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
              crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
              integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
              crossorigin="anonymous">
        <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="{% static 'js/subscribe.js' %}"></script>
    </head>
    <title>
        Registration Form
    </title>
    <body>
    <div class="form-block col-sm-4">
        {% csrf_token %}
        {{ subscribe_form }}
        <div id="statusForm"></div>
        <br>
        <button class="button" name="submit" id='subs-button' disabled>Submit</button>
    </div>
    </body>
    </html>
{% endblock %}

lab_3/templates/to_do_list.html
{% extends "navbar.html" %}
{% block content %}
    {% load staticfiles %}

    <html>
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
              integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
              crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
              integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
              crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/status.css' %}">
        <title>
            Landing Page
        </title>
    </head>
    <body>
    <div style="padding-top: 20px"></div>
    <form class="box" method="POST" action="{% url 'lab_3:add_status' %}">
        {% csrf_token %}
        {{ status.status }}
        <button type="submit" class="srch-btn" id="submit"><i class="fas fa-share"></i>
        </button>
    </form>
    <div style="padding-top: 500px"></div>
    <h1 style="margin-left: 39%" name="heading"> Hello, How Are You ?</h1>
    <div style="padding-bottom: 40px" name="cardgap"></div>
    {% for item in events %}
        <div class="card shadow"
             style="margin-left:41%; width: 18rem; border-radius: 32px; padding:15px; margin-bottom:32px;">
            <div class="card-body">
                <h3 class="card-title"> {{ item.forms }} </h3>
                <a href="{% url 'lab_3:delete' item.id %}" class="btn btn-primary">delete</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}
</body>
</html>