lab_3/urls.py
from django.urls import path
from .views import *

# Create your views here.
app_name = "lab_3"

urlpatterns = [
    path('', index, name="index"),
    path('add_status', add_status, name="add_status"),
    path('myprofile', myprofile, name="myprofile"),
    path('registro', registro, name="registro"),
    path('check_email/', check_email, name='check_email'),
    path('save_subscriber/', save_subscriber, name='save_subscriber'),
    path('list-subscriber/', listSubscriber, name='listSubscriber'),
    path('delete/<int:id>', bigdelete, name='delete')
]

ppw/urls.py
from django.contrib import admin
from django.urls import path, include
import story4.urls as story4
import story9.urls as story9

app_name="tryout2"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('story4/', include((story4, story4), namespace="story4")),
    path('', include("lab_3.urls", "lab_3")),
    path('library/', include((story9, story9), namespace='story9')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('tryout/', include("tryout.urls","tryout")),
    path('deathnote/', include("tryout2.urls","tryout2"))
]

story4/urls.py
from django.urls import path

from .views import index,profile,register,add_schedule,scheduling,show,erase
app_name = "story4"
urlpatterns = [
    path(r'',index, name="landing-page"),
    path(r'profile',profile, name="profile"),
    path(r'register',register, name="register"),
    path(r'add_schedule',add_schedule, name="add_schedule"),
    path(r'scheduling',scheduling, name="scheduling"),
    path(r'show',show,name="show"),
    path(r'erase',erase,name="erase"),
]

templates/base.html
{% load staticfiles %}
<html>
<head>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/logo.css' %}">
</head>
<body>
<header>
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'story4:landing-page' %}">HOME</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'story4:show' %}">My Schedule</a>
                        <a class="dropdown-item" href="{% url 'story4:scheduling' %}">Add Activity</a>
                        <a class="dropdown-item" href="{% url 'story4:erase' %}">Erase All Activity</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
</header>
{% block content %}
{% endblock %}

</body>
<footer>
    <div class="logo">
        <a href="www.twitter.com/irbahhana"><img src="{% static 'image/twitter.png' %}" height="50" width="50"></a>
        <a href="https://www.facebook.com/naufal.irbahhana"><img src="{% static 'image/facebook.png' %}" height="50"
                                                                 width="50"></a>
        <a href="https://www.linkedin.com/in/muhammad-naufal-irbahhana-651317147/"><img
                src="{% static 'image/linkedin.png' %}" height="50" width="50"></a>
        <a href="www.instagram.com"><img src="{% static 'image/instagram.png' %}" height="50" width="50"></a>
    </div>
</footer>

</html>

templates/navbar.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
{#     <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">#}
{#    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"#}
{#          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">#}
{#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>#}
{#    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>#}
{#    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>#}
{#    <script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>#}
{#    <link href="https://fonts.googleapis.com/css?family=Raleway:400,300,600,800,900" rel="stylesheet" type="text/css">#}
</head>
<body>
<div id="progressbar"></div>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'lab_3:index' %}">Status <span class="sr-only">(current)</span></a>
                </li>
                <li class=" nav-item">
                    <a class="nav-link" href="{% url 'lab_3:myprofile' %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'lab_3:registro' %}">Registration</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'story9:index' %}">Library</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

{% block content %}
{% endblock %}

</body>
</html>