ppw/urls.py
from django.contrib import admin
from django.urls import path, include
import story4.urls as story4
import story9.urls as story9

app_name="tryout2"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('story4/', include((story4, story4), namespace="story4")),
    path('', include("lab_3.urls", "lab_3")),
    path('library/', include((story9, story9), namespace='story9')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('tryout/', include("tryout.urls","tryout")),
    path('deathnote/', include("tryout2.urls","tryout2"))
]

story4/urls.py
from django.urls import path

from .views import index,profile,register,add_schedule,scheduling,show,erase
app_name = "story4"
urlpatterns = [
    path(r'',index, name="landing-page"),
    path(r'profile',profile, name="profile"),
    path(r'register',register, name="register"),
    path(r'add_schedule',add_schedule, name="add_schedule"),
    path(r'scheduling',scheduling, name="scheduling"),
    path(r'show',show,name="show"),
    path(r'erase',erase,name="erase"),
]

story4/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Schedule(models.Model):
    activity = models.CharField(max_length=200)
    datetime = models.DateField()
    time = models.TimeField()
    locations = models.CharField(max_length=200)
    category = models.CharField(max_length=200)

story4/forms.py
from django import forms
from django.utils import timezone

class Forms(forms.Form):
    activity_attrs = { 
        "type":"text",
        "placeholder":"Activity Name",
        "name":"activity",
        "value":"",
    }
    calendar_attrs = {
        "type":"date",
        "name":"datetime",
        "value":"",
    }
    locations_attrs = {
        "type":"text",
        "placeholder":"Location",
        "name":"location",
        "value":"",
    }
    category_attrs = {
        "type":"text",
        "placeholder":"Category",
        "name":"category",
        "value":"",
    }
    time_attrs = {
        "type":"time",
        "name":"time",
        "value":"",
    }
    activity = forms.CharField(max_length=200, required = True, widget=forms.TextInput(attrs=activity_attrs))
    datetime = forms.DateField(initial=timezone.now, required = True, widget=forms.DateInput(attrs=calendar_attrs))
    time = forms.TimeField(initial=timezone.now, required=True,widget=forms.TimeInput(attrs=time_attrs))
    locations = forms.CharField(max_length=200, required = True,widget=forms.TextInput(attrs=locations_attrs))
    category = forms.CharField(max_length=200, required = True,widget=forms.TextInput(attrs=category_attrs))

story4/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Schedule
from .forms import Forms
from django.urls import reverse



# Create your views here.

def index(request):
    return render(request,"landing-page.html")

def profile(request):
    return render(request,"profile.html")

def register(request):
    return render(request,"register.html")

def scheduling(request):
	response = {'schedule_form' : Forms
	}
	return render(request, "formschedule.html", response)

def add_schedule(request):
	forms = Forms(request.POST)
	if(request.method == 'POST'):
		if(forms.is_valid()):
			clean = forms.cleaned_data
			schedule = Schedule()
			schedule.activity = clean['activity']
			schedule.datetime = clean['datetime']
			schedule.locations = clean['locations']
			schedule.category = clean['category']
			schedule.time = clean['time']
			schedule.save()
			return HttpResponseRedirect(reverse('story4:show'))

def show(request):
	response = {
	'schedule' : Schedule.objects.all()
	}
	return render(request,"showschedule.html",response)

def erase(request):
	Schedule.objects.all().delete()
	return HttpResponseRedirect(reverse('story4:show'))

story4/templates/formschedule.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}

<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/register.css' %}">
        <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    </head>
    <title>
        Create Your Schedule !
    </title>
    <body>
        <div class="regisbox">
            <h1>
                Create Your Schedule !
            </h1>

            <form method="POST" action="{% url 'story4:add_schedule' %}">
            {% csrf_token %}
            <div class="textbox">
                <i class="fas fa-plane-departure"></i>
                {{schedule_form.activity}}
                {% comment %} <input type="text" placeholder="Activity Name" name="activity" value="" required> {% endcomment %}
            </div>
            <div class="textbox">
                <i class="far fa-calendar"></i>
                {{schedule_form.datetime}}
                {% comment %} <input type="datetime-local" name="datetime" value=""> {% endcomment %}
            </div>
            <div class="textbox">
                <i class="far fa-clock"></i>
                {{schedule_form.time}}
            </div>
            <div class="textbox">
                <i class="fas fa-map-marker-alt"></i>
                {{schedule_form.locations}}
                {% comment %} <input type="text" name="location" value="" placeholder="Location" required> {% endcomment %}
            </div>
            <div class="textbox">
                <i class="fas fa-exclamation"></i>
                {{schedule_form.category}}
                {% comment %} <input type="text" placeholder="Category" name="category" value="" required> {% endcomment %}
            </div>
        <button class="btn btn-outline-secondary btn-lg " aria-pressed="true" style="padding-top:3px;" type="submit">Register</a>
        </div>
    </form>
    </body>
    
</html>
{% endblock %}

story4/templates/landing-page.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
 <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style2.css' %}">
</head>
<title>
    Landing Page
</title>
        <div class="container" style="margin-left: 0;">
            <div>
                <h1 style="font-size:70px;text-align:center;">Muhammad Naufal Irbahhana</h1>
                <div class="container2">
                    <a href="{% url 'story4:profile'%}" class="btn btn-outline-secondary btn-lg " role="button" aria-pressed="true">My Profile</a>
                    <a href="{% url 'story4:register'%}" class="btn btn-outline-secondary btn-lg " role="button" aria-pressed="true">Register</a>
                </div>
            </div>
        </div>
{% endblock %}

story4/templates/profile.html
{% load staticfiles %}

<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    </head>
    <title>
        Profile
    </title>
    <body>
        <div class="class1" style="background-color:#000;">
            <a href="{% url 'story4:landing-page'%}" class="btn btn-outline-secondary btn-lg " role="button" aria-pressed="true" style="padding-top:3px;">Back</a>
            <div style="padding-right:1rem">
                <h1 style="color:white; text-align:right; padding-top:2rem">MUHAMMAD</h1>
                <h1 style="color:#c4c4c4; text-align:right; ">NAUFAL</h1>
                <h1 style="color:white; text-align:right;">IRBAHHANA</h1>
                <h2 style="color:white; text-align:right;padding-top:10px">1706019425</h2>
            </div>
            <hr>
            <p>Address: BSD Blok H-4 No 6 Sektor 1-1 Tangerang Selatan Banten</p>
            <p>Phone Number: 087871786040</p>
            <p>Majoring: Computer Science</p>
            <p>Hobbies: Sports, Video game, Singing</p>
            <p>Motto: Melakukan segala hal dengan nama Allah</p>
            <p>Bio :I am a bright and happy person, i tend to cheer people. 
                    Also a hardworker and passionate student.</p>
        </div>

        <div class="class2" style="background-color:white;">
            <div class="center">
                <img src="{% static 'image/me.jpeg' %}" class="rounded-circle mx-auto d-block" height="250" width="200">
                <h1 style="text-align:center;">SKILLS</h1>
            </div> 
            <div class="picture" style="padding-top:4rem">
                <img src="{% static 'image/skills.png' %}" class="rounded mx-auto d-block"height="200" width="400">
            </div>
        </div>

        <div class="class3">
            <img src="{% static 'image/pengalaman.png' %}"/>
        </div>
    </body>
</html>

story4/templates/register.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}

<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/register.css' %}">
        <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    </head>
    <title>
        Registration Form
    </title>
    <body>
        <div class="regisbox">
            <h1>
                Register
            </h1>
            <form>
            <div class="textbox">
                <i class="far fa-user"></i>
                <input type="text" placeholder="Name" name="" value="" required>
            </div>
            <div class="textbox">
                <i class="far fa-calendar"></i>
                <input type="date" name="" value="">
            </div>
            <div class="textbox">
                <i class="far fa-envelope"></i>
                <input type="email" name="" value="" placeholder="Email" required>
            </div>
            <div class="textbox">
                <i class="fas fa-at"></i>
                <input type="text" placeholder="Username" name="" value="" required>
            </div>
            <div class="textbox">
                <i class="fas fa-key"></i>
                <input type="password" placeholder="Password" name="" value="" required>
            </div>
            <div class="textbox">
                <i class="fas fa-unlock"></i>
                <input type="password" placeholder="Retype Password" name="" value="">
            </div>
        <button class="btn btn-outline-secondary btn-lg " aria-pressed="true" style="padding-top:3px;" type="submit">Register</a>
        </div>
    </form>
    </body>
    
</html>
{% endblock %}

story4/templates/showschedule.html
{% extends "base.html" %} {% block content %} {% load staticfiles %}

<head> 
<title> Your Schedule</title>
<link rel="stylesheet" href="{% static 'css/background.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
</head>
<body>
<div style="padding: 100px;">
<h1> MY SCHEDULE </h1>
<div style="margin-top:34px;">
{% for item in schedule %}
    <div class="card shadow" style="width: 18rem; border-radius: 32px; padding:15px; margin-bottom:32px;">
        <div class="card-body">
            <h3 class="card-title">    {{item.activity}} </h3>
            <h4 class="card-subtitle mb-2 text-muted">{{item.datetime}}><br>
            <i class="fas fa-map-marker-alt"></i> {{item.locations}} <br>
            <i class="far fa-clock"></i>{{item.time}} <br>
            <i class="fas fa-exclamation"></i> {{item.category}}
            </h4>
        </div>
    </div>
{% endfor %}
</div>
</div>

</body>
{% endblock %}