ppw/urls.py
from django.contrib import admin
from django.urls import path, include
import story4.urls as story4
import story9.urls as story9

app_name="tryout2"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('story4/', include((story4, story4), namespace="story4")),
    path('', include("lab_3.urls", "lab_3")),
    path('library/', include((story9, story9), namespace='story9')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('tryout/', include("tryout.urls","tryout")),
    path('deathnote/', include("tryout2.urls","tryout2"))
]

story9/urls.py
from django.urls import path
from story9.views import index,logout,inc,dec

app_name = "story9"

urlpatterns=[
    path('', index,name="index"),
    path('logout/', logout, name='logout'),
]

story9/models.py
from django.db import models
# Create your models here.

story9/views.py
from django.contrib.sites import requests
from django.shortcuts import render
from django.http import JsonResponse, HttpResponseRedirect



# Create your views here.
def index(request):
    if request.user.is_authenticated:
        request.session['user'] = request.user.username
        request.session['email'] = request.user.email
        request.session.get('counter', 0)
        print(dict(request.session))
        for key, value in request.session.items():
            print('{} => {}'.format(key, value))
    return render(request, "library.html")


def get_data(request, find="quilting"):
    link = "https://www.googleapis.com/books/v1/volumes?q=" + find
    print(link)
    data_final = requests.get(link).json()
    return JsonResponse(data_final)


def logout(request):
    """Logs out user"""
    request.session.flush()
    return HttpResponseRedirect('/library')


def inc(request):
    print(dict(request.session))
    request.session['counter'] = request.session['counter'] + 1
    return HttpResponseRedirect(request.session['counter'], content_type='application/json')


def dec(request):
    print(dict(request.session))
    request.session['counter'] = request.session['counter'] - 1
    return HttpResponseRedirect(request.session['counter'], content_type='application/json')

story9/templates/library.html
{% load staticfiles %}

<html>
<head>
    <title>Library</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          ntegrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="{% static "js/books.js" %}"></script>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <meta name="google-signin-client_id"
          content="710278269268-e13s6rtrpf24f8mhp739b99f8mq0ft6v..apps.googleusercontent.com">
</head>
<body style="background-color: #B5838D">

<script>
function handle(e){
    if(e.keyCode ===13){
        e.preventDefault()
        document.getElementById('myBtn').click()
    }
}
</script>

<div align="center" style="background-color: #6D6875">
    {% if user.is_authenticated %}
        <h1 style="font-size:100px ; font-family: Arial, Helvetica, sans-serif;color: #F0E6EF;">
            Hello, {{ user.username }} </h1>
    {% else %}
        <a href="{% url 'social:begin' backend='google-oauth2' %}">Login with Google</a><br>
    {% endif %}
    <h3 style="font-family: Arial, Helvetica, sans-serif;color: #F0E6EF">Find your favorite book here !</h3>
    <text style="font-size: 24px;font-family: Arial, Helvetica, sans-serif;color: #F0E6EF">Favourite(s):</text>
    <text style="font-size: 24px; font-family: Arial, Helvetica, sans-serif;color: #F0E6EF" id="counter">0</text>
    <input class="form-control form form-control-borderless" id="search-query" type="text"
            onkeypress="handle(event)" placeholder="Search topics or keywords"> <br>
    <button class="btn btn-lg "type="submit" id="myBtn" onclick='look()'>Search</button>
    <hr>
</div>
{% if user.is_authenticated %}
    <a href="{% url 'story9:logout' %}">Logout</a>
{% endif %}
<div class="table">
    <table id="bookTable" class="table table-hover table-responsive table-dark" style="background-color: #B5838D">
        <thead>
        <tr>
            <th scope="col">Thumbnail</th>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Publisher</th>
            <th scope="col">Favorite</th>
        </tr>
        </thead>
    </table>
</div>
</body>
</html>